# Generated by Django 5.1.3 on 2024-11-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('do_not_display_tab', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('auc_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('bid_time', models.CharField(blank=True, max_length=255, null=True)),
                ('time_of_bid', models.CharField(blank=True, max_length=255, null=True)),
                ('time_of_bid_unix', models.IntegerField(blank=True, null=True)),
                ('buyer_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('buyer_premium', models.FloatField(blank=True, null=True)),
                ('current_bid', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('highbidder_username', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bidding_status', models.CharField(blank=True, max_length=255, null=True)),
                ('end_time_unix', models.IntegerField(blank=True, null=True)),
                ('is_favorite', models.IntegerField(blank=True, null=True)),
                ('bid_count', models.IntegerField(blank=True, null=True)),
                ('viewed', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('item_bid_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_split', models.CharField(blank=True, max_length=255, null=True)),
                ('max_desired_bid', models.FloatField(blank=True, null=True)),
                ('bids', models.ManyToManyField(blank=True, to='auto_bid.bid')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('expense_input_form_link', models.URLField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, to='auto_bid.item')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('start_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aff_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state_abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('items', models.ManyToManyField(blank=True, to='auto_bid.item')),
            ],
        ),
    ]
