# Generated by Django 5.1.3 on 2024-11-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUserInput',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('end_time_unix', models.IntegerField(blank=True, null=True)),
                ('item_bid_group_id', models.TextField(blank=True, null=True)),
                ('ibg_items_to_win', models.IntegerField(blank=True, null=True)),
                ('cost_split', models.TextField(blank=True, null=True)),
                ('max_desired_bid', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
