# Generated by Django 5.1.3 on 2024-11-10 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUserInput',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('end_time_unix', models.IntegerField(blank=True, null=True)),
                ('item_bid_group_id', models.TextField(blank=True, null=True)),
                ('ibg_items_to_win', models.IntegerField(blank=True, null=True)),
                ('cost_split', models.TextField(blank=True, null=True)),
                ('max_desired_bid', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='affiliate',
            old_name='id',
            new_name='affiliate_id',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='id',
            new_name='auction_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='id',
            new_name='invoice_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='items',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost_split',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_bid_group_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='max_desired_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='firstname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='lastname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='aff_company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='affiliate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_bid.affiliate'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_datetime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='state_abbreviation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='zip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_id',
            field=models.CharField(default=0, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='buyer_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_bid.item'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='time_of_bid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='item_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auto_bid.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='expense_input_form_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='auction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_bid.auction'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bidding_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='highbidder_username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
