# Generated by Django 5.1.3 on 2024-11-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bid', '0002_itemuserinput_items_in_bid_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemuserinput',
            name='bidding_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemuserinput',
            name='current_bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemuserinput',
            name='highbidder_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
